services:
  dynamic-readme:
    container_name: dr-dev-app
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /usr/src/app
    volumes:
      - ./config.json:/usr/src/app/config.json
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=development
      # - NO_COMMIT=true
    command: npm run start:dev
    ports:
      - 3000:${APP_PORT}
